name: flutter_sherpa_onnx_example
description: Demonstrates how to use the sherpa_onnx_dart plugin with a Flutter app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sherpa_onnx_dart:
    path: ../../
  path_provider:
  flutter_ffi_asset_helper:
    git:
      url: https://github.com/nmfisher/flutter_ffi_asset_helper.git
  permission_handler:
  just_audio: 
  cupertino_icons: ^1.0.2
  wave_builder:
    git:
      url: https://github.com/nmfisher/wave_builder.git
  record: 5.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter
dependency_overrides:
  win32: 5.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/    
    - assets/model/    